version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/usr/src/auth-serive
      - /usr/src/auth-serive/node_modules
    ports:
      - "1081:1081"