FROM node:18.20.3
LABEL maintainer="jana.ru.sidorova@yandex.ru"
ENV NODE_ENV=development PORT=1081

RUN mkdir -p /usr/src/auth-service
WORKDIR /usr/src/auth-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

EXPOSE 1081

COPY ./bin/dev-docker-entrypoint.sh /bin/dev-docker-entrypoint.sh

RUN chmod +x /bin/dev-docker-entrypoint.sh

ENTRYPOINT ["/bin/dev-docker-entrypoint.sh"]