FROM node:14.17.0
LABEL maintainer="jana.ru.sidorova@yandex.ru"
ENV NODE_ENV=development PORT=1081

WORKDIR /usr/src/auth-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

EXPOSE 1081
CMD ["./node_modules/.bin/nodemon", "index.js"]